packages:
  # workspace packages
  - packages/**

  # exclude packages that are inside test directories
  - "!**/__fixtures__/**"
  - "!**/__test__/**"

# Define a catalog of version ranges.
catalog:
  dedent: ^1.7.0
  dotenv: ^17.2.2
  execa: ^9.6.0
  fs-extra: ^11.3.2
  has-unicode: ^2.0.1
  normalize-path: ^3.0.0
  npm-package-arg: ^13.0.0
  npm-registry-fetch: ^19.0.0
  p-map: ^7.0.3
  p-pipe: ^4.0.0
  semver: ^7.7.2
  slash: ^5.1.0

# add a few named catalog: for Lerna-Lite to test its own code with real projects
catalogs:
  # Can be referenced through "catalog:devDependencies"
  devDependencies:
    "@types/dedent": ^0.7.2
    "@types/fs-extra": ^11.0.4
    "@types/node": ^22.18.4
    "@types/npm-package-arg": ^6.1.4
    "@types/npmcli__package-json": ^4.0.4
    "@types/pacote": ^11.1.8
    "@types/semver": ^7.7.1
    "@types/yargs-parser": ^21.0.3
    yargs-parser: ^22.0.0

  # Can be referenced through "catalog:dependencies"
  dependencies:
    columnify: ^1.6.0
    load-json-file: ^7.0.1
    picomatch: ^4.0.3
    tinyglobby: ^0.2.15
    tinyrainbow: ^3.0.3
    uuid: ^11.1.0
    write-json-file: ^7.0.0
    write-package: ^7.2.0
    yaml: ^2.8.1
    yargs: ^18.0.0
    zeptomatch: ^2.0.2
