packages:
  # workspace packages
  - packages/**
  
  # e2e utilities (not published)
  - e2e-utils

  # exclude packages that are inside test directories
  - "!**/__fixtures__/**"
  - "!**/__test__/**"

# Define a catalog of version ranges.
catalog:
  ci-info: ^4.4.0
  dedent: ^1.7.1
  dotenv: ^17.2.3
  execa: ^9.6.1
  fs-extra: ^11.3.3
  has-unicode: ^2.0.1
  normalize-path: ^3.0.0
  npm-package-arg: ^13.0.2
  npm-registry-fetch: ^19.1.1
  p-map: ^7.0.4
  p-pipe: ^4.0.0
  semver: ^7.7.3
  slash: ^5.1.0

# add a few named catalog: for Lerna-Lite to test its own code with real projects
catalogs:
  # Can be referenced through "catalog:devDependencies"
  devDependencies:
    "@types/dedent": ^0.7.2
    "@types/fs-extra": ^11.0.4
    "@types/node": ^24.10.10
    "@types/npm-package-arg": ^6.1.4
    "@types/npmcli__package-json": ^4.0.4
    "@types/pacote": ^11.1.8
    "@types/semver": ^7.7.1
    "@types/yargs-parser": ^21.0.3
    yargs-parser: ^22.0.0

  # Can be referenced through "catalog:dependencies"
  dependencies:
    columnify: ^1.6.0
    load-json-file: ^7.0.1
    tinyglobby: ^0.2.15
    tinyrainbow: ^3.0.3
    uuid: ^13.0.0
    write-json-file: ^7.0.0
    write-package: ^7.2.0
    yaml: ^2.8.2
    yargs: ^18.0.0
    zeptomatch: ^2.1.0

overrides:
  vite: 8.0.0-beta.8