packages:
  # workspace packages
  - packages/**

  # exclude packages that are inside test directories
  - "!**/__fixtures__/**"
  - "!**/__test__/**"

# Define a catalog of version ranges.
catalog:
  "@types/dedent": ^0.7.2
  "@types/fs-extra": ^11.0.4
  "@types/minimatch": ^5.1.2
  "@types/node": ^22.15.21
  "@types/npm-package-arg": ^6.1.4
  "@types/semver": ^7.7.0
  columnify: ^1.6.0
  dedent: ^1.6.0
  dotenv: ^16.5.0
  execa: ^9.5.3
  fs-extra: ^11.3.0
  has-unicode: ^2.0.1
  load-json-file: ^7.0.1
  minimatch: ^10.0.1
  normalize-path: ^3.0.0
  npm-package-arg: ^12.0.2
  npm-registry-fetch: ^18.0.2
  p-map: ^7.0.3
  p-pipe: ^4.0.0
  semver: ^7.7.2
  slash: ^5.1.0
  temp-dir: ^3.0.0
  tinyglobby: ^0.2.13
  tinyrainbow: ^2.0.0
  write-json-file: ^6.0.0
  write-package: ^7.1.0
  yargs: ^18.0.0
  yargs-parser: ^22.0.0