name: 🐞 Bug report
description: Report an issue with Lerna-Lite
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a way to reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) would be nice unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: lerna-log
    attributes:
      label: Lerna config and logs
      description: provide your `lerna.json` config and `lerna-debug.log`
      value: |
        <details><summary>lerna.json</summary><p>
        <!-- browsers demand the next line be empty -->

        ```json
        <!-- Please paste your `lerna.json` here -->
        ```
        </p></details>

        <details><summary>lerna-debug.log</summary><p>
        <!-- browsers demand the next line be empty -->

        ```txt
        <!-- If you have a `lerna-debug.log` available, please paste it here -->
        <!-- Otherwise, feel free to delete this <details> block -->
        ```
        </p></details>
  - type: textarea
    id: system-info
    attributes:
      label: Environment Info
      description: versions number of each systems and libs (Lerna-Lite/[packageName], TypeScript)
      render: shell
      value: |
        | Executable        | Version |
        | ----------------- | ------- |
        | `lerna --version` | VERSION |
        | `npm --version`   | VERSION |
        | `yarn --version`  | VERSION |
        | `node --version`  | VERSION |

        ---
        OR simply run `npx lerna info` command
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - npm
        - yarn 1.x (classic)
        - yarn >= 2.x
        - pnpm
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/ghiscoding/lerna-lite/blob/master/.github/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [docs](https://github.com/ghiscoding/lerna-lite#readme).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/ghiscoding/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/lerna-lite/discussions).
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true