packages:
  - "packages/*"

# Define a catalog of version ranges.
catalog:
  package-1: '2.3.4'
  fs-extra: '^11.2.0'
  pkg-1: '1.0.0'
  p-map: '^7.0.3'
  tinyrainbow: '^2.0.0'

catalogs:
  # Can be referenced through "catalog:react17"
  react17:
    react: ^17.0.2
    react-dom: ^17.0.2

  # Can be referenced through "catalog:react18"
  react18:
    react: ^18.2.0
    react-dom: ^18.2.0