export const CHOKIDAR_AVAILABLE_OPTIONS = [
  'alwaysStat',
  'atomic',
  'awaitWriteFinish',
  'binaryInterval',
  'cwd',
  'depth',
  'disableGlobbing',
  'followSymlinks',
  'ignored',
  'ignoreInitial',
  'ignorePermissionErrors',
  'interval',
  'persistent',
  'usePolling',
];
