packages:
  - "packages/*"

# Define a catalog of version ranges.
catalog:
  package-1: 2.3.3
  fs-extra: ^11.1.0
  pkg-1: 1.0.0
  p-map: ^7.0.3
  tinyrainbow: ^2.0.0

catalogs:
  # Can be referenced through "catalog:react18"
  react18:
    react: ^18.3.2
    react-dom: ^18.3.1

  # Can be referenced through "catalog:react19"
  react19:
    react: ^19.0.1
    react-dom: ^19.0.1